name: Playwright Tests
on:
  push:
    branches:
    - reddit
jobs:

  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '14.x'
    - name: Install dependencies
      run: npm ci
    - name: Install certificates
      run: sudo apt-get install ca-certificates
    - name: Who Am I?
      run: whoami
    - name: Decrypt coookies
      env: 
        GPGKey: ${{ secrets.gpg_key }}
      run: |
        export GPG_TTY=$(tty)
        sudo echo -n "$GPGKey" | base64 --decode | gpg --batch --import 
        sudo chmod 777 ~/.gnupg
        sudo chown -R runner.runner ~/.gnupg
        sudo gpg --list-secret-keys
        sudo gpg -d --batch --passphrase-file passphrase.txt --output auth.json auth.json.gpg
        ls -a
    - name: Install Playwright
      run: npx playwright install --with-deps
    - name: Run Playwright tests
      run: npx playwright test
    - uses: actions/upload-artifact@v2
      if: always()
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30
